### ISSUE TITLE
Unable to pull the docker image 

### ISSUE THREAD

**Issue by AmyrAhmady** [keivanipchihagh/xui-trojan#1]
This is what I'm getting when I run `build.sh`

```
Pulling xui (registry.keivanipchihagh.com/x-ui:beta)...
ERROR: received unexpected HTTP status: 503 Service Temporarily Unavailable
```

**Comment by keivanipchihagh** [comment]
I just pulled the image with no problems.
Try running `docker pull registry.keivanipchihagh.com/x-ui:beta` in terminal and then the script.

**Comment by AmyrAhmady** [comment]
Sorry for my late response, yes, it indeed does work, it was an issue from my end.
